packages:
  - "server"
  - "client"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "bcrypt"
  - "prisma"
  - "esbuild"
  - "sharp"
  - "unrs-resolver"

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  bcrypt: true
  prisma: true
  esbuild: true
  sharp: true
  unrs-resolver: true
